version: "3"

services:
    web:
        container_name: app_node
        restart: "no"
        build: .
        ports:
            - "4000:4000"
        links:
            - database
        volumes:
            - .:/usr/src/app
    database:
        container_name: mongodb
        image: mongo
        ports:
            - "27017:27017"
        logging:
            driver: none
