version: "3"

services:
    web:
        container_name: app_node
        restart: always
        build: .
        ports:
            - "4000:4000"
        links:
            - database
        volumes:
            - .:/usr/src/app
    database:
        container_name: mongodb
        image: mongo
        restart: on-failure
        volumes:
            - mongo-data:/data/db
        ports:
            - "27017:27017"
        logging:
            driver: none
volumes:
    mongo-data: